run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic
    - gosec
    - revive

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
  
  gofmt:
    simplify: true
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  
  revive:
    rules:
      - name: exported
        severity: warning
      - name: error-return
      - name: error-naming
      - name: if-return
      - name: var-naming
      - name: package-comments

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude errcheck for os.Unsetenv in test files (cleanup in defer)
    - path: _test\.go
      linters:
        - errcheck
      text: "Error return value of `os.Unsetenv` is not checked"
    # Exclude errcheck for Close() in test files (cleanup in defer)
    - path: _test\.go
      linters:
        - errcheck
        - govet
      text: "(Error return value|declaration of \"err\" shadows)"
